// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Types$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Types";
  readonly sourceName: "contracts/Types.sol";
  readonly abi: [];
  readonly bytecode: "0x6055604b600b8282823980515f1a607314603f577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea26469706673582212208ed85ec83a8e59c89195202be4c5103276e625992084baa41b543bf19bfb0cc864736f6c634300081e0033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f5ffdfea26469706673582212208ed85ec83a8e59c89195202be4c5103276e625992084baa41b543bf19bfb0cc864736f6c634300081e0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/Types.sol";
  readonly buildInfoId: "solc-0_8_30-972082e6b455d4a9bc67c3d799dc97418f8bf30d";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Types"]: Types$Type;
    ["contracts/Types.sol:Types"]: Types$Type;
  }
}